name: todo_list_example
description: Un nuevo proyecto Flutter con Clean Architecture y buenas prácticas.
publish_to: "none" # Evita la publicación accidental en pub.dev
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  go_router: ^17.1.0
  hive: ^2.2.3
  json_annotation: ^4.11.0
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.2
  uuid: ^4.5.3
  very_good_analysis: ^10.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3

# Configuración específica de Flutter.
flutter:
  uses-material-design: true

  # Para añadir assets como imágenes, descomenta la siguiente sección:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para añadir fuentes personalizadas, descomenta la siguiente sección:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
